version: '3'

services:
  gs-app:
    build:
      context: .
    ports:
      - 8080:8080

  test-runner:
    image: alpine
    depends_on:
      - gs-app
    command: >
        sh -c "
               apk -U add curl &&
               curl --fail -v --retry 10 --retry-connrefused --retry-delay 5 http://gs-app:8080/health
               "
