version: '3'

services:
  gs-app:
    build:
      context: .
    depends_on:
      - influxdb
    ports:
      - 8080:8080
    environment:
      DB_URL: http://influxdb:8086

  influxdb:
    image: influxdb
    environment:
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXDB_DB=mydb
    ports:
      - 8086:8086
    volumes:
      - ./data:/var/lib/influxdb

  test-runner:
    image: alpine
    depends_on:
      - gs-app
    command: >
        sh -c "
               apk -U add curl &&
               curl --fail -v --retry 10 --retry-connrefused --retry-delay 5 http://gs-app:8080/health
               "
